-- +goose Up
CREATE TABLE integration_credentials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration TEXT NOT NULL,
  credential_key TEXT NOT NULL,
  ciphertext BYTEA NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (integration, credential_key)
);

CREATE TABLE integration_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('active', 'resolved')),
  summary TEXT NOT NULL,
  detail TEXT,
  first_triggered_at TIMESTAMPTZ NOT NULL,
  last_triggered_at TIMESTAMPTZ NOT NULL,
  resolved_at TIMESTAMPTZ,
  failure_count INTEGER NOT NULL DEFAULT 1 CHECK (failure_count > 0),
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (integration)
);

CREATE TRIGGER integration_credentials_set_updated_at
  BEFORE UPDATE ON integration_credentials
  FOR EACH ROW
  EXECUTE FUNCTION set_row_updated_at();

CREATE TRIGGER integration_alerts_set_updated_at
  BEFORE UPDATE ON integration_alerts
  FOR EACH ROW
  EXECUTE FUNCTION set_row_updated_at();

-- +goose Down
DROP TRIGGER IF EXISTS integration_alerts_set_updated_at ON integration_alerts;
DROP TRIGGER IF EXISTS integration_credentials_set_updated_at ON integration_credentials;

DROP TABLE IF EXISTS integration_alerts;
DROP TABLE IF EXISTS integration_credentials;
