-- +goose Up
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION set_row_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username CITEXT NOT NULL,
  email CITEXT NOT NULL,
  real_name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending_verification' CHECK (status IN ('pending_verification', 'active', 'disabled')),
  email_verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (username),
  UNIQUE (email)
);

CREATE TABLE platform_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  platform TEXT NOT NULL CHECK (platform IN ('codeforces', 'atcoder', 'luogu')),
  handle CITEXT NOT NULL,
  display_handle TEXT,
  status TEXT NOT NULL DEFAULT 'pending_review' CHECK (status IN ('pending_review', 'verified', 'disabled', 'rejected')),
  verified_at TIMESTAMPTZ,
  last_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (platform, handle)
);

CREATE TABLE platform_account_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform_account_id BIGINT NOT NULL REFERENCES platform_accounts (id) ON DELETE CASCADE,
  reviewer_user_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
  from_status TEXT,
  to_status TEXT NOT NULL CHECK (to_status IN ('pending_review', 'verified', 'disabled', 'rejected')),
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE sync_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_user_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
  platform_account_id BIGINT REFERENCES platform_accounts (id) ON DELETE SET NULL,
  platform TEXT CHECK (platform IS NULL OR platform IN ('codeforces', 'atcoder', 'luogu', 'icpc', 'clist')),
  job_type TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  scheduled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  error_message TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE platform_profile_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform_account_id BIGINT NOT NULL REFERENCES platform_accounts (id) ON DELETE CASCADE,
  source TEXT NOT NULL,
  display_name TEXT,
  rating INTEGER,
  max_rating INTEGER,
  profile_url TEXT,
  raw_payload_ref TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  fetched_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE accepted_event_raw (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_user_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
  platform_account_id BIGINT REFERENCES platform_accounts (id) ON DELETE SET NULL,
  platform TEXT NOT NULL CHECK (platform IN ('codeforces', 'atcoder', 'luogu')),
  handle CITEXT NOT NULL,
  problem_key TEXT NOT NULL,
  contest_id TEXT,
  problem_index_or_task_id TEXT,
  problem_name TEXT,
  problem_url TEXT,
  accepted_at TIMESTAMPTZ NOT NULL,
  submission_id_or_ref TEXT,
  source TEXT NOT NULL,
  source_url TEXT,
  raw_payload_ref TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE problem_facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  platform TEXT NOT NULL CHECK (platform IN ('codeforces', 'atcoder', 'luogu')),
  problem_key TEXT NOT NULL,
  contest_id TEXT,
  problem_index_or_task_id TEXT,
  problem_name TEXT,
  problem_url TEXT,
  first_ac_at TIMESTAMPTZ NOT NULL,
  first_ac_source TEXT NOT NULL,
  first_ac_submission_ref TEXT,
  first_ac_event_raw_id BIGINT REFERENCES accepted_event_raw (id) ON DELETE SET NULL,
  latest_ac_at TIMESTAMPTZ NOT NULL,
  clist_problem_id BIGINT,
  clist_contest_id BIGINT,
  clist_rating INTEGER,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (first_ac_at <= latest_ac_at),
  UNIQUE (site_user_id, platform, problem_key)
);

CREATE TABLE contest_ac_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  platform TEXT NOT NULL CHECK (platform IN ('codeforces', 'atcoder', 'luogu')),
  contest_id TEXT NOT NULL,
  contest_name TEXT,
  ac_problem_keys TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  ac_count INTEGER NOT NULL DEFAULT 0 CHECK (ac_count >= 0),
  first_ac_at TIMESTAMPTZ,
  last_ac_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (site_user_id, platform, contest_id)
);

CREATE TABLE award_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  platform TEXT NOT NULL DEFAULT 'icpc' CHECK (platform = 'icpc'),
  contest_name TEXT NOT NULL,
  award_name TEXT NOT NULL,
  rank_text TEXT,
  award_date DATE NOT NULL,
  source TEXT NOT NULL,
  source_url TEXT,
  is_manual BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (site_user_id, platform, contest_name, award_name, award_date)
);

CREATE TABLE clist_problem_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform TEXT NOT NULL CHECK (platform IN ('codeforces', 'atcoder')),
  problem_key TEXT NOT NULL,
  clist_problem_id BIGINT NOT NULL,
  clist_contest_id BIGINT,
  clist_resource_id BIGINT,
  clist_resource_name TEXT,
  problem_name TEXT,
  problem_url TEXT,
  rating INTEGER,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (platform, problem_key),
  UNIQUE (clist_problem_id)
);

CREATE TABLE atcoder_extension_sync_states (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  platform_account_id BIGINT NOT NULL REFERENCES platform_accounts (id) ON DELETE CASCADE,
  atcoder_handle CITEXT NOT NULL,
  last_success_synced_at TIMESTAMPTZ,
  last_attempt_synced_at TIMESTAMPTZ,
  last_extension_sync_status TEXT NOT NULL DEFAULT 'idle' CHECK (last_extension_sync_status IN ('idle', 'running', 'success', 'failed')),
  last_window_from TIMESTAMPTZ,
  last_window_to TIMESTAMPTZ,
  last_uploaded_count INTEGER NOT NULL DEFAULT 0 CHECK (last_uploaded_count >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (platform_account_id)
);

CREATE TABLE user_platform_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  platform TEXT NOT NULL CHECK (platform IN ('codeforces', 'atcoder', 'luogu')),
  verified_account_count INTEGER NOT NULL DEFAULT 0 CHECK (verified_account_count >= 0),
  solved_count INTEGER NOT NULL DEFAULT 0 CHECK (solved_count >= 0),
  display_rating INTEGER,
  last_aggregated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (site_user_id, platform)
);

CREATE TABLE user_rating_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  snapshot_at TIMESTAMPTZ NOT NULL,
  at_best_score NUMERIC(10, 4) NOT NULL DEFAULT 0,
  at_recent_score NUMERIC(10, 4) NOT NULL DEFAULT 0,
  at_training_score NUMERIC(10, 4) NOT NULL DEFAULT 0,
  cf_best_score NUMERIC(10, 4) NOT NULL DEFAULT 0,
  cf_recent_score NUMERIC(10, 4) NOT NULL DEFAULT 0,
  cf_training_score NUMERIC(10, 4) NOT NULL DEFAULT 0,
  recent_score NUMERIC(10, 4) NOT NULL DEFAULT 0,
  scnu_rating NUMERIC(10, 4) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (site_user_id, snapshot_at)
);

CREATE TABLE leaderboard_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_type TEXT NOT NULL CHECK (snapshot_type IN ('daily_close', 'current')),
  snapshot_date DATE NOT NULL,
  snapshot_at TIMESTAMPTZ NOT NULL,
  site_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  rank INTEGER NOT NULL CHECK (rank > 0),
  at_training_score NUMERIC(10, 4) NOT NULL DEFAULT 0,
  cf_training_score NUMERIC(10, 4) NOT NULL DEFAULT 0,
  recent_score NUMERIC(10, 4) NOT NULL DEFAULT 0,
  scnu_rating NUMERIC(10, 4) NOT NULL DEFAULT 0,
  today_new_accepted_count INTEGER NOT NULL DEFAULT 0 CHECK (today_new_accepted_count >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (snapshot_type, snapshot_date, site_user_id)
);

CREATE TABLE heatmap_daily_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  stat_date DATE NOT NULL,
  new_accepted_count INTEGER NOT NULL DEFAULT 0 CHECK (new_accepted_count >= 0),
  platform_breakdown JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (site_user_id, stat_date)
);

CREATE INDEX users_real_name_trgm_idx ON users USING GIN (real_name gin_trgm_ops);
CREATE INDEX platform_accounts_site_user_idx ON platform_accounts (site_user_id, platform, status);
CREATE INDEX platform_account_reviews_account_idx ON platform_account_reviews (platform_account_id, created_at DESC);
CREATE INDEX sync_jobs_status_idx ON sync_jobs (status, scheduled_at);
CREATE INDEX sync_jobs_platform_account_idx ON sync_jobs (platform_account_id, created_at DESC);
CREATE INDEX platform_profile_snapshots_account_idx ON platform_profile_snapshots (platform_account_id, fetched_at DESC);
CREATE INDEX accepted_event_raw_site_user_idx ON accepted_event_raw (site_user_id, platform, accepted_at DESC);
CREATE INDEX accepted_event_raw_platform_account_idx ON accepted_event_raw (platform_account_id, accepted_at DESC);
CREATE INDEX accepted_event_raw_problem_idx ON accepted_event_raw (platform, problem_key, accepted_at);
CREATE INDEX accepted_event_raw_contest_idx ON accepted_event_raw (platform, contest_id, accepted_at);
CREATE UNIQUE INDEX accepted_event_raw_submission_ref_unique_idx ON accepted_event_raw (platform, handle, source, submission_id_or_ref) WHERE submission_id_or_ref IS NOT NULL;
CREATE UNIQUE INDEX accepted_event_raw_fallback_unique_idx ON accepted_event_raw (platform, handle, source, problem_key, accepted_at) WHERE submission_id_or_ref IS NULL;
CREATE INDEX problem_facts_first_ac_idx ON problem_facts (site_user_id, platform, first_ac_at);
CREATE INDEX problem_facts_clist_idx ON problem_facts (platform, clist_problem_id);
CREATE INDEX contest_ac_summaries_lookup_idx ON contest_ac_summaries (site_user_id, platform, contest_id);
CREATE INDEX award_records_site_user_idx ON award_records (site_user_id, award_date DESC);
CREATE INDEX atcoder_extension_sync_states_user_idx ON atcoder_extension_sync_states (site_user_id, updated_at DESC);
CREATE INDEX user_platform_stats_lookup_idx ON user_platform_stats (site_user_id, platform);
CREATE INDEX user_rating_snapshots_lookup_idx ON user_rating_snapshots (site_user_id, snapshot_at DESC);
CREATE INDEX leaderboard_snapshots_rank_idx ON leaderboard_snapshots (snapshot_type, snapshot_date, rank);
CREATE INDEX heatmap_daily_stats_lookup_idx ON heatmap_daily_stats (site_user_id, stat_date DESC);

CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION set_row_updated_at();

CREATE TRIGGER platform_accounts_set_updated_at
  BEFORE UPDATE ON platform_accounts
  FOR EACH ROW
  EXECUTE FUNCTION set_row_updated_at();

CREATE TRIGGER sync_jobs_set_updated_at
  BEFORE UPDATE ON sync_jobs
  FOR EACH ROW
  EXECUTE FUNCTION set_row_updated_at();

CREATE TRIGGER problem_facts_set_updated_at
  BEFORE UPDATE ON problem_facts
  FOR EACH ROW
  EXECUTE FUNCTION set_row_updated_at();

CREATE TRIGGER contest_ac_summaries_set_updated_at
  BEFORE UPDATE ON contest_ac_summaries
  FOR EACH ROW
  EXECUTE FUNCTION set_row_updated_at();

CREATE TRIGGER clist_problem_mappings_set_updated_at
  BEFORE UPDATE ON clist_problem_mappings
  FOR EACH ROW
  EXECUTE FUNCTION set_row_updated_at();

CREATE TRIGGER atcoder_extension_sync_states_set_updated_at
  BEFORE UPDATE ON atcoder_extension_sync_states
  FOR EACH ROW
  EXECUTE FUNCTION set_row_updated_at();

CREATE TRIGGER user_platform_stats_set_updated_at
  BEFORE UPDATE ON user_platform_stats
  FOR EACH ROW
  EXECUTE FUNCTION set_row_updated_at();

CREATE TRIGGER heatmap_daily_stats_set_updated_at
  BEFORE UPDATE ON heatmap_daily_stats
  FOR EACH ROW
  EXECUTE FUNCTION set_row_updated_at();

-- +goose Down
DROP TRIGGER IF EXISTS heatmap_daily_stats_set_updated_at ON heatmap_daily_stats;
DROP TRIGGER IF EXISTS user_platform_stats_set_updated_at ON user_platform_stats;
DROP TRIGGER IF EXISTS atcoder_extension_sync_states_set_updated_at ON atcoder_extension_sync_states;
DROP TRIGGER IF EXISTS clist_problem_mappings_set_updated_at ON clist_problem_mappings;
DROP TRIGGER IF EXISTS contest_ac_summaries_set_updated_at ON contest_ac_summaries;
DROP TRIGGER IF EXISTS problem_facts_set_updated_at ON problem_facts;
DROP TRIGGER IF EXISTS sync_jobs_set_updated_at ON sync_jobs;
DROP TRIGGER IF EXISTS platform_accounts_set_updated_at ON platform_accounts;
DROP TRIGGER IF EXISTS users_set_updated_at ON users;

DROP TABLE IF EXISTS heatmap_daily_stats;
DROP TABLE IF EXISTS leaderboard_snapshots;
DROP TABLE IF EXISTS user_rating_snapshots;
DROP TABLE IF EXISTS user_platform_stats;
DROP TABLE IF EXISTS atcoder_extension_sync_states;
DROP TABLE IF EXISTS clist_problem_mappings;
DROP TABLE IF EXISTS award_records;
DROP TABLE IF EXISTS contest_ac_summaries;
DROP TABLE IF EXISTS problem_facts;
DROP TABLE IF EXISTS accepted_event_raw;
DROP TABLE IF EXISTS platform_profile_snapshots;
DROP TABLE IF EXISTS sync_jobs;
DROP TABLE IF EXISTS platform_account_reviews;
DROP TABLE IF EXISTS platform_accounts;
DROP TABLE IF EXISTS users;

-- +goose StatementBegin
DROP FUNCTION IF EXISTS set_row_updated_at();
-- +goose StatementEnd
