-- +goose Up
CREATE TABLE platform_contest_histories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  platform_account_id BIGINT REFERENCES platform_accounts (id) ON DELETE SET NULL,
  platform TEXT NOT NULL CHECK (platform IN ('codeforces', 'atcoder')),
  contest_id TEXT NOT NULL,
  contest_name TEXT NOT NULL,
  rank INTEGER,
  old_rating INTEGER,
  new_rating INTEGER,
  rating_delta INTEGER,
  participated_at TIMESTAMPTZ NOT NULL,
  source TEXT NOT NULL,
  source_url TEXT,
  raw_payload_ref TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (platform_account_id, platform, contest_id)
);

CREATE INDEX platform_contest_histories_user_idx
  ON platform_contest_histories (site_user_id, platform, participated_at DESC);

CREATE TRIGGER platform_contest_histories_set_updated_at
  BEFORE UPDATE ON platform_contest_histories
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- +goose Down
DROP TRIGGER IF EXISTS platform_contest_histories_set_updated_at ON platform_contest_histories;
DROP TABLE IF EXISTS platform_contest_histories;
